name: Deploy to GCP
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy agent-handler \
            --runtime python310 \
            --trigger-topic agent-events \
            --entry-point main \
            --memory 512MB \
            --region us-central1 \
            --source src/ \
            --set-env-vars FIRESTORE_PROJECT=${{ secrets.GCP_PROJECT_ID }},PUBSUB_TOPIC=agent-events
      - name: Terraform Apply (Infrastructure)
        run: |
          cd iac
          terraform init
          terraform apply -auto-approve -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -var "region=us-central1" -var "functions_bucket=${{ secrets.FUNCTIONS_BUCKET }}" -var "functions_object=${{ secrets.FUNCTIONS_OBJECT }}"
